# Getting and Cleaning Data Course Project

# First Try
setwd("F:/Data Science/Getting and Cleaning Data/Project")
fileUrl<-"http://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileUrl,destfile="Dataset.zip")
unzip("Dataset.zip",exdir=".")
setwd("./UCI HAR Dataset/test")
test<-read.table("X_test.txt",header=FALSE,stringsAsFactor=FALSE)
dim(test)
subject<-read.table("subject_test.txt")
dim(subject)
activity<-read.table("y_test.txt")
dim(activity)
test<-cbind(test,subject,activity)
head(test,2)
dim(test)
train<-read.table("../train/X_train.txt",header=FALSE,stringsAsFactor=FALSE)
dim(train)
subject2<-read.table("../train/subject_train.txt")
dim(subject2)
activity2<-read.table("../train/y_train.txt")
dim(activity2)
train<-cbind(train,subject2,activity2)
dim(train)
data<-rbind(test,train)
features<-read.table("../features.txt",stringsAsFactor=FALSE)
dim(features)
class(features[,2])
colnames(data)<-c(features[,2],"Subject","Activity")
names(data)
head(data,2)
labels<-read.table("../activity_labels.txt")
data$Activity<-factor(data$Activity,labels=labels[,2])
data$Activity

N1<-grep("mean",names(data),fixed=TRUE,value=TRUE)
N2<-grep("std",names(data),fixed=TRUE,value=TRUE)
N<-c(N1,N2)
which(names(data)%in% N)
dataSub<-data[,c(which(names(data)%in% N),562,563)]
names(dataSub)
dim(dataSub)
table()
tapply(dataSub[,1:79],dataSub$Activity,mean)
dim(dataSub)
L1<-split(dataSub[,1:79],dataSub$Activity)
sapply(L1[1],mean)
sapply(as.data.frame(L1[2]),mean)

write.table(dataSub,"../dataSub.csv")

library(reshape2)
library(plyr)
melted<-melt(dataSub,id=c("Subject","Activity"))
head(melted,3)
dim(melted)
Finally<-ddply(melted, c("Subject", "Activity"), summarise,mean = mean(value), sd = sd(value))
Finally2<-ddply(melted, c("Activity", "Subject"), summarise,mean = mean(value), sd = sd(value))
Finally2
write.table(Finally,"../Finally.csv")
write.table(Finally2,"../Finally2.csv")

Finally<-read.table("./UCI HAR Dataset/Finally.txt")
Finally


# 整理之后
setwd("F:/Data Science/Getting and Cleaning Data/Project/UCI HAR Dataset/test")
test<-read.table("X_test.txt",header=FALSE,stringsAsFactor=FALSE)
subject<-read.table("subject_test.txt")
activity<-read.table("y_test.txt")
test<-cbind(test,subject,activity)
train<-read.table("../train/X_train.txt",header=FALSE,stringsAsFactor=FALSE)
subject2<-read.table("../train/subject_train.txt")
activity2<-read.table("../train/y_train.txt")
train<-cbind(train,subject2,activity2)
data<-rbind(test,train)
features<-read.table("../features.txt",stringsAsFactor=FALSE)
colnames(data)<-c(features[,2],"Subject","Activity")
labels<-read.table("../activity_labels.txt")
data$Activity<-factor(data$Activity,labels=labels[,2])
N1<-grep("mean",names(data),fixed=TRUE,value=TRUE)
N2<-grep("std",names(data),fixed=TRUE,value=TRUE)
N<-c(N1,N2)
dataSub<-data[,c(which(names(data)%in% N),562,563)]
library(reshape2)
library(plyr)
melted<-melt(dataSub,id=c("Subject","Activity"))
Finally<-ddply(melted, c("Subject", "Activity"), summarise,mean = mean(value), sd = sd(value))
Finally2<-ddply(melted, c("Activity", "Subject"), summarise,mean = mean(value), sd = sd(value))
write.table(Finally,"../Finally.csv")
write.table(Finally2,"../Finally2.csv")

